import { ormFetch } from '../_shared/orm-fetch.js';
export default [
  { name: 'list_ar_entries', description: 'List Accounts Receivable entries with filters, sorting, pagination. IMPORTANT: For "outstanding", "open", "unpaid", or "overdue" queries, ALWAYS set filters.tag_closed_yn to "n" to exclude already-paid items.', parameters: { type: 'object', properties: { filters: { type: 'object', properties: { party_code: { type: 'string' }, party_desc: { type: 'string' }, maint_date_trans: { type: 'string' }, date_from: { type: 'string', description: 'Start date filter (YYYY-MM-DD or YYYY-MM for whole month, e.g. "2026-04" for April 2026). Use for "this month", "last month", date range queries.' }, date_to: { type: 'string', description: 'End date filter (exclusive). Same format as date_from.' }, maint_date_due: { type: 'string' }, maint_acctnumdisp: { type: 'string' }, maint_curr_short: { type: 'string' }, maint_cslsegm: { type: 'string' }, date_trans: { type: 'string' }, tag_closed_yn: { type: 'string', description: '"n" = open/outstanding/unpaid, "y" = closed/paid. MUST use "n" for outstanding balance queries.' }, tag_void_yn: { type: 'string' }, amount_min: { type: 'number' }, amount_max: { type: 'number' } }, description: 'Keys: party_code, party_desc (text search), maint_date_trans, maint_date_due, maint_acctnumdisp, maint_curr_short, maint_cslsegm (source type), date_trans, tag_closed_yn ("n"=open/outstanding, "y"=closed/paid — ALWAYS use "n" for outstanding queries), tag_void_yn. amount_min (number, exclude zero/low amounts), amount_max (number, cap amounts).' }, sortField: { type: 'string', description: 'Sort by: maint_date_trans, maint_date_due, maint_amount_local, party_code, date_trans.' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, page: { type: 'number', description: 'Page number.' }, pageSize: { type: 'number', description: 'Max 20.' } }, required: [] },
    async func(args) { return ormFetch('list', 'accounts_receivable', { filters: args.filters || {}, sortField: args.sortField || 'maint_date_trans', sortDir: args.sortDir || 'DESC', page: args.page || 1, pageSize: Math.min(args.pageSize || 10, 20) }); } },
  { name: 'get_ar_entry', description: 'Get a single AR entry by ID.', parameters: { type: 'object', properties: { id: { type: 'string', description: 'uniquenum_pri.' } }, required: ['id'] },
    async func(args) { return ormFetch('findById', 'accounts_receivable', { id: args.id }); } },
  { name: 'count_ar_entries', description: 'Count AR entries matching filters.', parameters: { type: 'object', properties: { filters: { type: 'object', description: 'Same as list_ar_entries.' } }, required: [] },
    async func(args) { return ormFetch('count', 'accounts_receivable', { filters: args.filters || {} }); } },
  { name: 'aggregate_ar_entries', description: 'Summarize AR — total receivable by customer, currency, source type, date. Use for aging and outstanding balance analysis. IMPORTANT: For "outstanding", "open", "unpaid" queries, ALWAYS set filters.tag_closed_yn to "n".', parameters: { type: 'object', properties: { func: { type: 'string', description: 'sum, count, avg, min, max.' }, measure: { type: 'string', description: 'maint_amount_local, maint_amount_forex, or maint_amount_orig.' }, groupBy: { type: 'string', description: 'party_code, party_desc, maint_acctnumdisp, maint_curr_short, maint_cslsegm, maint_date_trans, tag_closed_yn.' }, filters: { type: 'object', description: 'Same as list_ar_entries. For outstanding/open/unpaid queries, MUST include tag_closed_yn: "n".' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, limit: { type: 'number', description: 'Max 50.' } }, required: [] },
    async func(args) { return ormFetch('aggregate', 'accounts_receivable', { func: args.func || 'sum', measure: args.measure || 'maint_amount_local', groupBy: args.groupBy || '', filters: args.filters || {}, sortDir: args.sortDir || 'DESC', limit: Math.min(args.limit || 10, 50) }); } }
];
