import { ormFetch } from '../_shared/orm-fetch.js';
export default [
  { name: 'list_gl_entries', description: 'List General Ledger journal entries with filters. Always filter by date or account — this is a high-volume table.', parameters: { type: 'object', properties: { filters: { type: 'object', properties: { acctnumdisp: { type: 'string' }, party_code: { type: 'string' }, party_desc: { type: 'string' }, date_trans: { type: 'string' }, date_from: { type: 'string', description: 'Start date filter (YYYY-MM-DD or YYYY-MM for whole month, e.g. "2026-04" for April 2026). Use for "this month", "last month", date range queries.' }, date_to: { type: 'string', description: 'End date filter (exclusive). Same format as date_from.' }, date_post: { type: 'string' }, fyearcfn: { type: 'string' }, periodmth_cfn: { type: 'string' }, staff_code: { type: 'string' }, deptunit_code: { type: 'string' }, location_code: { type: 'string' }, cslsegm: { type: 'string' }, tag_void_yn: { type: 'string' }, tag_wflow_app_yn: { type: 'string' }, amount_min: { type: 'number' }, amount_max: { type: 'number' } }, description: 'Keys: acctnumdisp (GL account code), party_code, party_desc (text search), date_trans, date_post, fyearcfn (fiscal year), periodmth_cfn (period), staff_code, deptunit_code, location_code, cslsegm, tag_void_yn, tag_wflow_app_yn. amount_min (number, exclude zero/low amounts), amount_max (number, cap amounts).' }, sortField: { type: 'string', description: 'Sort by: date_trans, date_post, amount_local, acctnumdisp, party_code.' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, page: { type: 'number', description: 'Page number.' }, pageSize: { type: 'number', description: 'Max 20.' } }, required: [] },
    async func(args) { return ormFetch('list', 'general_ledger', { filters: args.filters || {}, sortField: args.sortField || 'date_trans', sortDir: args.sortDir || 'DESC', page: args.page || 1, pageSize: Math.min(args.pageSize || 10, 20) }); } },
  { name: 'get_gl_entry', description: 'Get a single GL journal entry by ID.', parameters: { type: 'object', properties: { id: { type: 'string', description: 'uniquenum_pri.' } }, required: ['id'] },
    async func(args) { return ormFetch('findById', 'general_ledger', { id: args.id }); } },
  { name: 'count_gl_entries', description: 'Count GL entries matching filters.', parameters: { type: 'object', properties: { filters: { type: 'object', description: 'Same as list_gl_entries.' } }, required: [] },
    async func(args) { return ormFetch('count', 'general_ledger', { filters: args.filters || {} }); } },
  { name: 'aggregate_gl_entries', description: 'Summarize GL entries — total/balance by account, party, department, period, date. Use for trial balance and account analysis. amount_local is SIGNED: positive=debit, negative=credit.', parameters: { type: 'object', properties: { func: { type: 'string', description: 'sum, count, avg, min, max.' }, measure: { type: 'string', description: 'amount_local or amount_forex.' }, groupBy: { type: 'string', description: 'acctnumdisp, party_code, party_desc, staff_code, deptunit_code, location_code, cslsegm, date_trans, fyearcfn, periodmth_cfn.' }, filters: { type: 'object', description: 'Same as list_gl_entries.' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, limit: { type: 'number', description: 'Max 50.' } }, required: [] },
    async func(args) { return ormFetch('aggregate', 'general_ledger', { func: args.func || 'sum', measure: args.measure || 'amount_local', groupBy: args.groupBy || '', filters: args.filters || {}, sortDir: args.sortDir || 'DESC', limit: Math.min(args.limit || 10, 50) }); } }
];
