import { ormFetch } from '../_shared/orm-fetch.js';
export default [
  { name: 'list_purchase_invoices', description: 'List purchase invoices (supplier invoices) with filters, sorting, pagination.', parameters: { type: 'object', properties: { filters: { type: 'object', properties: { party_code: { type: 'string' }, party_desc: { type: 'string' }, date_trans: { type: 'string' }, date_from: { type: 'string', description: 'Start date filter (YYYY-MM-DD or YYYY-MM for whole month, e.g. "2026-04" for April 2026). Use for "this month", "last month", date range queries.' }, date_to: { type: 'string', description: 'End date filter (exclusive). Same format as date_from.' }, staff_code: { type: 'string' }, dnum_auto: { type: 'string' }, curr_short_forex: { type: 'string' }, tag_void_yn: { type: 'string' }, amount_min: { type: 'number' }, amount_max: { type: 'number' } }, description: 'Keys: party_code, party_desc (text search), date_trans, staff_code, dnum_auto, curr_short_forex, tag_void_yn. amount_min (number, exclude zero/low amounts), amount_max (number, cap amounts).' }, sortField: { type: 'string', description: 'Sort by: date_trans, dnum_auto, party_code, amount_forex.' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, page: { type: 'number', description: 'Page number.' }, pageSize: { type: 'number', description: 'Max 20.' } }, required: [] },
    async func(args) { return ormFetch('list', 'purchase_invoice', { filters: args.filters || {}, sortField: args.sortField || 'date_trans', sortDir: args.sortDir || 'DESC', page: args.page || 1, pageSize: Math.min(args.pageSize || 10, 20) }); } },
  { name: 'get_purchase_invoice', description: 'Get a single purchase invoice by ID.', parameters: { type: 'object', properties: { id: { type: 'string', description: 'uniquenum_pri.' } }, required: ['id'] },
    async func(args) { return ormFetch('findById', 'purchase_invoice', { id: args.id }); } },
  { name: 'count_purchase_invoices', description: 'Count purchase invoices.', parameters: { type: 'object', properties: { filters: { type: 'object', description: 'Same as list.' } }, required: [] },
    async func(args) { return ormFetch('count', 'purchase_invoice', { filters: args.filters || {} }); } },
  { name: 'aggregate_purchase_invoices', description: 'Summarize purchase invoices by supplier, staff, currency, date, credit term.', parameters: { type: 'object', properties: { func: { type: 'string', description: 'sum, count, avg, min, max.' }, measure: { type: 'string', description: 'amount_forex or amount_local.' }, groupBy: { type: 'string', description: 'party_code, party_desc, staff_code, staff_desc, curr_short_forex, date_trans, creditterm_desc.' }, filters: { type: 'object', description: 'Same as list.' }, sortDir: { type: 'string', description: 'ASC or DESC.' }, limit: { type: 'number', description: 'Max 50.' } }, required: [] },
    async func(args) { return ormFetch('aggregate', 'purchase_invoice', { func: args.func || 'sum', measure: args.measure || 'amount_local', groupBy: args.groupBy || '', filters: args.filters || {}, sortDir: args.sortDir || 'DESC', limit: Math.min(args.limit || 10, 50) }); } }
];
